const OPERATORS_VEHICLE_REQUEST =  "OPERATORS_VEHICLE_REQUEST" 
const OPERATORS_VEHICLE_SUCCESS =  "OPERATORS_VEHICLE_SUCCESS" 
const OPERATORS_VEHICLE_FAILURE =  "OPERATORS_VEHICLE_FAILURE" 

const OPERATORS_POST_VEHICLE_REQUEST =  "OPERATORS_POST_VEHICLE_REQUEST" 
const OPERATORS_POST_VEHICLE_SUCCESS =  "OPERATORS_POST_VEHICLE_SUCCESS" 
const OPERATORS_POST_VEHICLE_FAILURE =  "OPERATORS_POST_VEHICLE_FAILURE" 

export default {
    OPERATORS_VEHICLE_REQUEST,
    OPERATORS_VEHICLE_SUCCESS,
    OPERATORS_VEHICLE_FAILURE,
    OPERATORS_POST_VEHICLE_REQUEST,
    OPERATORS_POST_VEHICLE_SUCCESS,
    OPERATORS_POST_VEHICLE_FAILURE
}