const USER_REGISTER_REQUEST =  "USER_REGISTER_REQUEST" 
const USER_REGISTER_SUCCESS =  "USER_REGISTER_SUCCESS" 
const USER_REGISTER_FAILURE =  "USER_REGISTER_FAILURE" 

export default {
    USER_REGISTER_REQUEST,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAILURE
}