const USER_LOGIN_REQUEST =  "USER_LOGIN_REQUEST" 
const USER_LOGIN_SUCCESS =  "USER_LOGIN_SUCCESS" 
const USER_LOGIN_FAILURE =  "USER_LOGIN_FAILURE" 
const USER_LOGOUT = "USER_LOGOUT"
export default {
    USER_LOGIN_REQUEST,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILURE,
    USER_LOGOUT
}